# Generated by Django 3.2.23 on 2024-01-03 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eras', '0001_initial'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='era_preferences',
            field=models.ManyToManyField(blank=True, related_name='era_pref', to='eras.Era'),
        ),
    ]
