# Generated by Django 3.2.23 on 2024-01-03 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genres', '0001_initial'),
        ('profiles', '0002_profile_era_preferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='genre_preferences',
            field=models.ManyToManyField(blank=True, related_name='genre_pref', to='genres.Genre'),
        ),
    ]
