# Generated by Django 3.2.23 on 2024-01-04 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('profiles', '0003_profile_genre_preferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='category_preferences',
            field=models.ManyToManyField(blank=True, related_name='cat_pref', to='categories.Category'),
        ),
    ]
