# Generated by Django 3.2.23 on 2024-01-22 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('genres', '0001_initial'),
        ('eras', '0001_initial'),
        ('profiles', '0004_profile_category_preferences'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='category_preferences',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='era_preferences',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='genre_preferences',
        ),
        migrations.AddField(
            model_name='profile',
            name='category_preference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='categories.category'),
        ),
        migrations.AddField(
            model_name='profile',
            name='era_preference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eras.era'),
        ),
        migrations.AddField(
            model_name='profile',
            name='genre_preference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='genres.genre'),
        ),
    ]
