# Generated by Django 3.2.23 on 2024-01-28 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('eras', '0001_initial'),
        ('genres', '0001_initial'),
        ('profiles', '0006_auto_20240128_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='category_preference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='categories.category'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='era_preference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eras.era'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='genre_preference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='genres.genre'),
        ),
    ]
