# Generated by Django 3.2.23 on 2024-01-14 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snapshots', '0003_auto_20240112_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snapshot',
            name='image',
            field=models.ImageField(upload_to='images/snapshots/'),
        ),
    ]
