# Generated by Django 3.2.23 on 2024-01-03 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style', models.CharField(max_length=150)),
                ('summary', models.TextField(blank=True)),
                ('image', models.ImageField(default='../default_post_e32dts', upload_to='images/genres/')),
            ],
        ),
    ]
