# Generated by Django 3.2.23 on 2024-01-24 22:28

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='audio',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='auto'),
        ),
    ]
