# Generated by Django 3.2.23 on 2024-01-25 13:23

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0005_auto_20240125_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='audio',
            field=models.FileField(storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='audio/snapshots/'),
        ),
    ]
