# Generated by Django 3.2.23 on 2024-01-25 14:04

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0006_alter_sample_audio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='audio',
            field=models.ImageField(storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='audio/snapshots/'),
        ),
    ]
